### ISSUE TITLE
Add x-summary and x-project for catalog

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-openapi-samples#5]
## I wish

 - to support `info.x-summary` containing an one-liner for Catalog purposes
 - to add an `info.x-project` referencing the Team project (eg. `daf`)

## Notes

There's a proposal for `info.summary` in OpenAPI spec https://github.com/OAI/OpenAPI-Specification/issues/832#issuecomment-407108439

**Comment by tammynewbie** [comment]
Is there an easier way to understand how to do this? I am missing something of the "small" detail pm parts. I can understand etiology of it all.

**Comment by tammynewbie** [comment]
> ## I wish
> 
>  - to support `info.x-summary` containing an one-liner for Catalog purposes
>  - to add an `info.x-project` referencing the Team project (eg. `daf`)
> To be the inspector general of IoT
> ## Notes
> 
> There's a proposal for `info.summary` in OpenAPI spec https://github.com/OAI/OpenAPI-Specification/issues/832#issuecomment-407108439
